# ──────────────────────────────────────────────────────────────────────────────
# User-facing input variables
#
# DECISION: Variables grouped by concern, not alphabetically.
# Why: Related variables are easier to review and configure when adjacent.
#      Deploy-time variables (tokens, hostnames) come first; tuning knobs last.
# ──────────────────────────────────────────────────────────────────────────────

# ═══════════════════════════════════════════════════════════════════════════════
#  Credentials
# ═══════════════════════════════════════════════════════════════════════════════

variable "hcloud_api_token" {
  description = "Hetzner Cloud API token for the management project (read/write access required)"
  type        = string
  nullable    = false
  sensitive   = true
}

# ═══════════════════════════════════════════════════════════════════════════════
#  Rancher configuration
# ═══════════════════════════════════════════════════════════════════════════════

variable "rancher_hostname" {
  # DECISION: Optional — auto-generates a sslip.io hostname from the ingress LB IP when empty.
  # Why: Enables single `tofu apply` without pre-existing DNS. For production,
  #      set a real FQDN that resolves to the ingress LB IPv4.
  description = "FQDN for the Rancher UI (e.g. 'rancher.example.com'). Leave empty to auto-generate from ingress LB IP via sslip.io."
  type        = string
  nullable    = false
  default     = ""

  validation {
    condition     = var.rancher_hostname == trimspace(var.rancher_hostname)
    error_message = "rancher_hostname must not contain leading or trailing whitespace."
  }
}

variable "rancher_version" {
  description = "Rancher Helm chart version to install (e.g. '2.13.3'). Must be compatible with the Kubernetes version."
  type        = string
  nullable    = false
  default     = "2.13.3"

  validation {
    condition     = can(regex("^\\d+\\.\\d+\\.\\d+", var.rancher_version))
    error_message = "rancher_version must be a semantic version (e.g. '2.13.3')."
  }
}

variable "admin_password" {
  description = "Initial password for the Rancher 'admin' user. Must be at least 12 characters. Change immediately after first login."
  type        = string
  nullable    = false
  sensitive   = true

  validation {
    condition     = length(var.admin_password) >= 12
    error_message = "admin_password must be at least 12 characters for security."
  }
}

variable "tls_source" {
  description = "TLS certificate source for Rancher. 'rancher' = self-signed CA generated by Rancher, 'letsEncrypt' = Let's Encrypt via cert-manager ACME, 'secret' = user-provided TLS secret."
  type        = string
  nullable    = false
  default     = "rancher"

  validation {
    condition     = contains(["rancher", "letsEncrypt", "secret"], var.tls_source)
    error_message = "tls_source must be one of: rancher, letsEncrypt, secret."
  }
}

variable "letsencrypt_email" {
  description = "Email address for Let's Encrypt certificate registration. Required when tls_source = 'letsEncrypt', ignored otherwise."
  type        = string
  nullable    = false
  default     = ""

  # NOTE: Validation is relaxed — empty string is allowed when tls_source != letsEncrypt.
  # Cross-variable validation (tls_source + letsencrypt_email) is enforced in guardrails.tf.
}

variable "cert_manager_version" {
  description = "cert-manager Helm chart version to install."
  type        = string
  nullable    = false
  default     = "1.17.2"

  validation {
    condition     = can(regex("^\\d+\\.\\d+\\.\\d+", var.cert_manager_version))
    error_message = "cert_manager_version must be a semantic version (e.g. '1.17.2')."
  }
}

# ═══════════════════════════════════════════════════════════════════════════════
#  Hetzner Node Driver (zsys-studio)
# ═══════════════════════════════════════════════════════════════════════════════

variable "hetzner_driver_version" {
  description = "Version of zsys-studio/rancher-hetzner-cluster-provider to install as Rancher Node Driver."
  type        = string
  nullable    = false
  default     = "0.8.0"

  validation {
    condition     = can(regex("^\\d+\\.\\d+\\.\\d+", var.hetzner_driver_version))
    error_message = "hetzner_driver_version must be a semantic version (e.g. '0.8.0')."
  }
}

variable "install_hetzner_driver" {
  description = "Install the zsys-studio Hetzner Node Driver and UI Extension. Set to false if managing the driver separately."
  type        = bool
  nullable    = false
  default     = true
}

# ═══════════════════════════════════════════════════════════════════════════════
#  Cluster infrastructure
# ═══════════════════════════════════════════════════════════════════════════════

variable "cluster_name" {
  description = "Identifier prefix for all provisioned resources (servers, LBs, network, firewall). Must be lowercase alphanumeric, max 20 characters."
  type        = string
  nullable    = false
  default     = "rancher"

  validation {
    condition     = can(regex("^[a-z0-9]{1,20}$", var.cluster_name))
    error_message = "cluster_name must be lowercase alphanumeric and at most 20 characters."
  }
}

variable "management_node_count" {
  description = "Number of control-plane nodes for the management cluster. Use 1 for dev/test, 3 for HA production."
  type        = number
  nullable    = false
  default     = 1

  validation {
    condition     = var.management_node_count == 1 || var.management_node_count >= 3
    error_message = "management_node_count must be 1 (non-HA) or >= 3 (HA with etcd quorum). A value of 2 results in split-brain."
  }
}

variable "control_plane_server_type" {
  description = "Hetzner Cloud server type for management cluster nodes. Minimum cx43 (8 vCPU, 16 GB) for Rancher."
  type        = string
  nullable    = false
  default     = "cx43"
}

variable "node_location" {
  description = "Primary Hetzner datacenter location for management cluster nodes (e.g. 'hel1', 'nbg1', 'fsn1')."
  type        = string
  nullable    = false
  default     = "hel1"

  validation {
    condition     = length(var.node_location) > 0
    error_message = "node_location must not be empty."
  }
}

# ═══════════════════════════════════════════════════════════════════════════════
#  Network
# ═══════════════════════════════════════════════════════════════════════════════

variable "hcloud_network_cidr" {
  description = "IPv4 address range for the Hetzner private network in CIDR notation."
  type        = string
  nullable    = false
  default     = "10.0.0.0/16"

  validation {
    condition     = can(cidrnetmask(var.hcloud_network_cidr))
    error_message = "hcloud_network_cidr must be a valid CIDR block (e.g. 10.0.0.0/16)."
  }
}

variable "subnet_address" {
  description = "Subnet allocation for cluster nodes within the private network."
  type        = string
  nullable    = false
  default     = "10.0.1.0/24"

  validation {
    condition     = can(cidrnetmask(var.subnet_address))
    error_message = "subnet_address must be a valid CIDR block (e.g. 10.0.1.0/24)."
  }
}

variable "hcloud_network_zone" {
  description = "Hetzner network zone encompassing all node locations."
  type        = string
  nullable    = false
  default     = "eu-central"

  validation {
    condition     = contains(["eu-central", "us-east", "us-west", "ap-southeast"], var.hcloud_network_zone)
    error_message = "hcloud_network_zone must be one of: eu-central, us-east, us-west, ap-southeast."
  }
}

# ═══════════════════════════════════════════════════════════════════════════════
#  Security / Access control
# ═══════════════════════════════════════════════════════════════════════════════

# DECISION: ssh_allowed_cidrs removed.
# Why: rke2-core is Zero-SSH (ADR-002). No port 22 firewall rules are created.
#      Operators who need SSH access bring their own Hetzner SSH keys via rke2-core's
#      ssh_key_ids variable and manage firewall rules separately.
variable "k8s_api_allowed_cidrs" {
  description = "CIDR blocks allowed to access the Kubernetes API (port 6443). Default: open."
  type        = list(string)
  nullable    = false
  default     = ["0.0.0.0/0", "::/0"]

  validation {
    condition     = length(var.k8s_api_allowed_cidrs) > 0
    error_message = "k8s_api_allowed_cidrs must contain at least one CIDR block."
  }

  validation {
    condition     = alltrue([for c in var.k8s_api_allowed_cidrs : can(cidrsubnet(c, 0, 0))])
    error_message = "All k8s_api_allowed_cidrs entries must be valid CIDR blocks."
  }
}

# DECISION: enable_secrets_encryption removed.
# Why: rke2-core does not expose this variable. Secrets encryption is
#      configurable via the rke2_config pass-through variable if needed.

# ═══════════════════════════════════════════════════════════════════════════════
#  RKE2 / Kubernetes
# ═══════════════════════════════════════════════════════════════════════════════

variable "rke2_version" {
  description = "RKE2 release tag to deploy (e.g. 'v1.32.2+rke2r1'). Leave empty for stable channel."
  type        = string
  nullable    = false
  default     = "v1.32.2+rke2r1"

  validation {
    condition     = var.rke2_version == "" || can(regex("^v\\d+\\.\\d+\\.\\d+\\+rke2r\\d+$", var.rke2_version))
    error_message = "rke2_version must look like 'vX.Y.Z+rke2rN' (or be empty)."
  }
}
