# ──────────────────────────────────────────────────────────────────────────────
# User-facing input variables
#
# DECISION: Variables grouped by concern, not alphabetically.
# Why: Related variables are easier to review and configure when adjacent.
#      Deploy-time variables (tokens, hostnames) come first; tuning knobs last.
# ──────────────────────────────────────────────────────────────────────────────

# ═══════════════════════════════════════════════════════════════════════════════
#  Credentials
# ═══════════════════════════════════════════════════════════════════════════════

variable "hcloud_api_token" {
  description = "Hetzner Cloud API token for the management project (read/write access required)"
  type        = string
  nullable    = false
  sensitive   = true
}

# ═══════════════════════════════════════════════════════════════════════════════
#  Rancher configuration
# ═══════════════════════════════════════════════════════════════════════════════

variable "rancher_hostname" {
  # DECISION: Optional — auto-generates a sslip.io hostname from the ingress LB IP when empty.
  # Why: Enables single `tofu apply` without pre-existing DNS. For production,
  #      set a real FQDN that resolves to the ingress LB IPv4.
  description = "FQDN for the Rancher UI (e.g. 'rancher.example.com'). Leave empty to auto-generate from ingress LB IP via sslip.io."
  type        = string
  nullable    = false
  default     = ""

  validation {
    condition     = var.rancher_hostname == trimspace(var.rancher_hostname)
    error_message = "rancher_hostname must not contain leading or trailing whitespace."
  }
}

variable "rancher_version" {
  description = "Rancher Helm chart version to install (e.g. '2.13.3'). Must be compatible with the Kubernetes version."
  type        = string
  nullable    = false
  default     = "2.13.3"

  validation {
    condition     = can(regex("^\\d+\\.\\d+\\.\\d+", var.rancher_version))
    error_message = "rancher_version must be a semantic version (e.g. '2.13.3')."
  }
}

variable "admin_password" {
  # DECISION: Optional — auto-generates a random 24-char password when empty.
  # Why: Eliminates the manual input prompt during `tofu apply`. The generated
  #      password is exposed via the `rancher_admin_password` output (sensitive).
  #      For CI/CD pipelines, pass a specific password via TF_VAR_admin_password.
  description = "Initial password for the Rancher 'admin' user. Leave empty to auto-generate a secure random password (output as rancher_admin_password)."
  type        = string
  nullable    = false
  sensitive   = true
  default     = ""

  validation {
    condition     = var.admin_password == "" || length(var.admin_password) >= 12
    error_message = "admin_password must be at least 12 characters (or empty for auto-generation)."
  }

  # DECISION: Block YAML-breaking characters in user-provided passwords.
  # Why: The password is embedded in a HelmChart CRD valuesContent (YAML inside YAML).
  #      Characters like %, {, }, [, ], *, &, #, ?, |, >, <, `, " break YAML parsing.
  validation {
    condition     = var.admin_password == "" || can(regex("^[a-zA-Z0-9_.\\-!@^()+=/~]+$", var.admin_password))
    error_message = "admin_password contains characters that break YAML parsing (%, {, }, [, ], *, &, #, ?, |, >, <, `, \"). Use alphanumeric plus: - _ . ! @ ^ ( ) + = / ~"
  }
}

variable "tls_source" {
  description = "TLS certificate source for Rancher. 'rancher' = self-signed CA generated by Rancher, 'letsEncrypt' = Let's Encrypt via cert-manager ACME, 'secret' = user-provided TLS secret."
  type        = string
  nullable    = false
  default     = "rancher"

  validation {
    condition     = contains(["rancher", "letsEncrypt", "secret"], var.tls_source)
    error_message = "tls_source must be one of: rancher, letsEncrypt, secret."
  }
}

variable "letsencrypt_email" {
  description = "Email address for Let's Encrypt certificate registration. Required when tls_source = 'letsEncrypt', ignored otherwise."
  type        = string
  nullable    = false
  default     = ""

  validation {
    condition     = var.letsencrypt_email == "" || can(regex("@", var.letsencrypt_email))
    error_message = "letsencrypt_email must contain an @ symbol (or be empty)."
  }
}

variable "cert_manager_version" {
  description = "cert-manager Helm chart version to install."
  type        = string
  nullable    = false
  default     = "1.17.2"

  validation {
    condition     = can(regex("^\\d+\\.\\d+\\.\\d+", var.cert_manager_version))
    error_message = "cert_manager_version must be a semantic version (e.g. '1.17.2')."
  }
}

# ═══════════════════════════════════════════════════════════════════════════════
#  Hetzner Node Driver (zsys-studio)
# ═══════════════════════════════════════════════════════════════════════════════

variable "install_hetzner_driver" {
  description = "Install zsys-studio Hetzner Node Driver for downstream cluster provisioning via Rancher UI. Set to false if the driver is managed externally."
  type        = bool
  nullable    = false
  default     = true
}

variable "hetzner_driver_version" {
  description = "Version of zsys-studio/rancher-hetzner-cluster-provider to install as Rancher Node Driver."
  type        = string
  nullable    = false
  default     = "0.9.0"

  validation {
    condition     = can(regex("^\\d+\\.\\d+\\.\\d+", var.hetzner_driver_version))
    error_message = "hetzner_driver_version must be a semantic version (e.g. '0.9.0')."
  }
}

# ═══════════════════════════════════════════════════════════════════════════════
#  Hcloud Image Controller (DES-004)
# ═══════════════════════════════════════════════════════════════════════════════

variable "install_hcloud_image_controller" {
  description = "Install the Hcloud Image Controller for automated Packer snapshot builds when HetznerConfig uses 'golden:*' image convention. Requires Hetzner Node Driver."
  type        = bool
  nullable    = false
  default     = false
}

variable "hcloud_image_controller_version" {
  description = "Hcloud Image Controller Helm chart appVersion / container image tag."
  type        = string
  nullable    = false
  default     = "0.1.0"

  validation {
    condition     = can(regex("^\\d+\\.\\d+\\.\\d+", var.hcloud_image_controller_version))
    error_message = "hcloud_image_controller_version must be a semantic version (e.g. '0.1.0')."
  }
}

variable "hcloud_image_builder_version" {
  description = "Hcloud Image Builder container image tag (Packer + Ansible image used by builder Jobs)."
  type        = string
  nullable    = false
  default     = "0.1.0"

  validation {
    condition     = can(regex("^\\d+\\.\\d+\\.\\d+", var.hcloud_image_builder_version))
    error_message = "hcloud_image_builder_version must be a semantic version (e.g. '0.1.0')."
  }
}

variable "hcloud_image_rke2_version" {
  description = "Default RKE2 version baked into controller-triggered Packer snapshots. Used as DEFAULT_RKE2_VERSION env var in the controller."
  type        = string
  nullable    = false
  default     = "v1.34.4+rke2r1"

  validation {
    condition     = can(regex("^v\\d+\\.\\d+\\.\\d+\\+rke2r\\d+$", var.hcloud_image_rke2_version))
    error_message = "hcloud_image_rke2_version must look like 'vX.Y.Z+rke2rN'."
  }
}

# ═══════════════════════════════════════════════════════════════════════════════
#  Ingress Load Balancer (BYO pattern)
# ═══════════════════════════════════════════════════════════════════════════════

# DECISION: BYO pattern for ingress LB — create or use existing.
# Why: Follows the composable-primitive pattern from terraform-hcloud-rke2-core.
#      Production teams may pre-provision load balancers with specific IPs,
#      use external LB solutions, or share an LB across services.
# See: https://github.com/mbilan1/rke2-hetzner-architecture/blob/main/decisions/adr-003-dual-load-balancer.md
variable "create_ingress_lb" {
  description = "Create a Hetzner ingress load balancer for Rancher UI (ports 80/443). Set to false when using a pre-existing or external load balancer."
  type        = bool
  nullable    = false
  default     = true
}

variable "existing_ingress_lb_ipv4" {
  description = "IPv4 address of an existing ingress load balancer. Only used when create_ingress_lb = false. If set, auto-generates hostname from this IP (unless rancher_hostname is provided)."
  type        = string
  nullable    = false
  default     = ""

  validation {
    condition     = var.existing_ingress_lb_ipv4 == "" || can(cidrhost("${var.existing_ingress_lb_ipv4}/32", 0))
    error_message = "existing_ingress_lb_ipv4 must be a valid IPv4 address or empty."
  }
}

# ═══════════════════════════════════════════════════════════════════════════════
#  Cluster infrastructure
# ═══════════════════════════════════════════════════════════════════════════════

variable "cluster_name" {
  description = "Identifier prefix for all provisioned resources (servers, LBs, network). Must be lowercase alphanumeric with optional hyphens, max 20 characters."
  type        = string
  nullable    = false
  default     = "rancher"

  validation {
    condition     = can(regex("^[a-z][a-z0-9-]{0,18}[a-z0-9]$", var.cluster_name))
    error_message = "cluster_name must start with a letter, contain only lowercase alphanumeric and hyphens, not end with a hyphen, and be at most 20 characters."
  }
}

variable "management_node_count" {
  description = "Number of control-plane nodes for the management cluster. Use 1 for dev/test, 3 for HA production."
  type        = number
  nullable    = false
  default     = 1

  validation {
    condition     = var.management_node_count == 1 || var.management_node_count >= 3
    error_message = "management_node_count must be 1 (non-HA) or >= 3 (HA with etcd quorum). A value of 2 results in split-brain."
  }
}

variable "control_plane_server_type" {
  description = "Hetzner Cloud server type for management cluster nodes. Minimum cx43 (8 vCPU, 16 GB) for Rancher."
  type        = string
  nullable    = false
  default     = "cx43"
}

variable "node_location" {
  description = "Primary Hetzner datacenter location for management cluster nodes (e.g. 'hel1', 'nbg1', 'fsn1')."
  type        = string
  nullable    = false
  default     = "hel1"

  validation {
    condition     = contains(["nbg1", "fsn1", "hel1", "ash", "hil", "sin"], var.node_location)
    error_message = "Must be a valid Hetzner Cloud location: nbg1, fsn1, hel1, ash, hil, sin."
  }
}

# ═══════════════════════════════════════════════════════════════════════════════
#  Network
# ═══════════════════════════════════════════════════════════════════════════════

variable "hcloud_network_cidr" {
  description = "IPv4 address range for the Hetzner private network in CIDR notation."
  type        = string
  nullable    = false
  default     = "10.0.0.0/16"

  validation {
    condition     = can(cidrnetmask(var.hcloud_network_cidr))
    error_message = "hcloud_network_cidr must be a valid CIDR block (e.g. 10.0.0.0/16)."
  }
}

variable "subnet_address" {
  description = "Subnet allocation for cluster nodes within the private network."
  type        = string
  nullable    = false
  default     = "10.0.1.0/24"

  validation {
    condition     = can(cidrnetmask(var.subnet_address))
    error_message = "subnet_address must be a valid CIDR block (e.g. 10.0.1.0/24)."
  }
}

variable "hcloud_network_zone" {
  description = "Hetzner network zone encompassing all node locations."
  type        = string
  nullable    = false
  default     = "eu-central"

  validation {
    condition     = contains(["eu-central", "us-east", "us-west", "ap-southeast"], var.hcloud_network_zone)
    error_message = "hcloud_network_zone must be one of: eu-central, us-east, us-west, ap-southeast."
  }
}

# ═══════════════════════════════════════════════════════════════════════════════
#  Security / Access control
# ═══════════════════════════════════════════════════════════════════════════════

# DECISION: BYO Firewall — passthrough to rke2-core.
# Why: Hetzner firewalls are account-level singletons (ADR-006). Consumers
#      create firewalls externally and pass IDs via this variable. The IDs
#      are forwarded to rke2-core which attaches them to all cluster nodes.
# See: https://github.com/mbilan1/rke2-hetzner-architecture/blob/main/decisions/adr-006-byo-firewall.md
variable "firewall_ids" {
  description = "List of Hetzner firewall IDs to attach to all management cluster nodes. BYO: create firewalls externally and pass their IDs."
  type        = list(number)
  nullable    = false
  default     = []
}

# DECISION: BYO SSH Key — passthrough to rke2-core.
# Why: True Zero-SSH by default (ADR-002). Users who need SSH access for
#      debugging or compliance bring their own pre-existing Hetzner SSH key IDs.
variable "ssh_key_ids" {
  description = "List of Hetzner SSH key IDs to install on management cluster nodes. Empty by default (Zero-SSH)."
  type        = list(number)
  nullable    = false
  default     = []
}

# DECISION: enable_secrets_encryption removed.
# Why: rke2-core does not expose this variable. Secrets encryption is
#      configurable via the rke2_config pass-through variable if needed.

# ═══════════════════════════════════════════════════════════════════════════════
#  OS Image
# ═══════════════════════════════════════════════════════════════════════════════

variable "hcloud_image" {
  # DECISION: Feature flag for Packer baked images (CIS-hardened snapshots).
  # Why: Default is ubuntu-24.04 (standard cloud image). When a Packer snapshot
  #      ID is provided, all management cluster nodes use the pre-hardened image
  #      instead. This enables CIS Level 1 hardening at the OS layer without
  #      runtime modification.
  description = "OS image for management cluster nodes. Use 'ubuntu-24.04' (default) or a Hetzner snapshot ID from a Packer baked image."
  type        = string
  nullable    = false
  default     = "ubuntu-24.04"
}

# ═══════════════════════════════════════════════════════════════════════════════
#  RKE2 / Kubernetes
# ═══════════════════════════════════════════════════════════════════════════════

variable "rke2_config" {
  # DECISION: Passthrough for additional RKE2 server config.
  # Why: Enables operators to configure etcd S3 backup, audit logging,
  #      and other RKE2 server settings without modifying the module.
  #      Content is appended to every node's config.yaml.
  # NOTE: CIS profile is handled separately via enable_cis.
  #       Do NOT add 'profile: cis' here — use enable_cis instead.
  # NOTE: Default enables aggressive local etcd snapshots for management clusters.
  description = "Additional RKE2 config.yaml content appended to every management cluster node."
  type        = string
  nullable    = false
  default     = <<-EOT
    etcd-snapshot-schedule-cron: "0 */6 * * *"
    etcd-snapshot-retention: 10
  EOT
}

variable "enable_cis" {
  # DECISION: Single CIS feature flag for both Packer and Profile flows.
  # Why: RKE2 CIS profile requires OS-level prerequisites (etcd user, kernel
  #      params) that must be applied BEFORE rke2-server starts. This flag
  #      handles prereqs + profile atomically. Prerequisites are idempotent —
  #      safe on both stock images (cloud-init creates them) and Packer-built
  #      snapshots (already baked in by rke2-base Ansible role).
  #      Additionally creates cattle-system namespace with PSA 'privileged'
  #      exemption so Rancher pods pass PodSecurity admission.
  # See: https://docs.rke2.io/security/hardening_guide
  description = "Enable CIS hardening for the management cluster. Activates RKE2 CIS profile, creates prerequisites (etcd user, kernel params), and exempts cattle-system from PodSecurity restricted policy. Works with both stock ubuntu-24.04 and Packer-built snapshots."
  type        = bool
  nullable    = false
  default     = false
}

variable "rke2_version" {
  description = "RKE2 release tag to deploy (e.g. 'v1.34.4+rke2r1'). Leave empty for stable channel."
  type        = string
  nullable    = false
  default     = "v1.34.4+rke2r1"

  validation {
    condition     = var.rke2_version == "" || can(regex("^v\\d+\\.\\d+\\.\\d+\\+rke2r\\d+$", var.rke2_version))
    error_message = "rke2_version must look like 'vX.Y.Z+rke2rN' (or be empty)."
  }
}
